<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class news extends Model
{
    public static  function boot()
{
    parent::boot(); // TODO: Change the autogenerated stub
    // it will automatically add authenticate user to created_by column of selected model
    static::creating(function ($model){
        $model->authorID = auth()->user()->id;
        $model->authorName = auth()->user()->name;
    });
}

}
